# Generated by Django 3.0.5 on 2021-03-31 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userarea',
            options={'managed': True},
        ),
    ]
