# Generated by Django 3.0.5 on 2021-03-31 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaPacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateField(auto_now=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('hora_registro', models.TimeField(auto_now_add=True)),
                ('pregunta1', models.CharField(choices=[('E', 'EXCELENTE'), ('B', 'BUENO'), ('R', 'REGULAR'), ('M', 'MALO')], max_length=2)),
                ('pregunta2', models.CharField(choices=[('E', 'EXCELENTE'), ('B', 'BUENO'), ('R', 'REGULAR'), ('M', 'MALO')], max_length=2)),
                ('pregunta3', models.CharField(choices=[('E', 'EXCELENTE'), ('B', 'BUENO'), ('R', 'REGULAR'), ('M', 'MALO')], max_length=2)),
                ('pregunta4', models.CharField(choices=[('E', 'EXCELENTE'), ('B', 'BUENO'), ('R', 'REGULAR'), ('M', 'MALO')], max_length=2)),
                ('pregunta5', models.CharField(choices=[('E', 'EXCELENTE'), ('B', 'BUENO'), ('R', 'REGULAR'), ('M', 'MALO')], max_length=2)),
                ('pregunta6', models.CharField(choices=[('E', 'EXCELENTE'), ('B', 'BUENO'), ('R', 'REGULAR'), ('M', 'MALO')], max_length=2)),
                ('pregunta7', models.CharField(choices=[('E', 'EXCELENTE'), ('B', 'BUENO'), ('R', 'REGULAR'), ('M', 'MALO')], max_length=2)),
                ('pregunta8', models.CharField(choices=[('E', 'EXCELENTE'), ('B', 'BUENO'), ('R', 'REGULAR'), ('M', 'MALO')], max_length=2)),
                ('pregunta9', models.CharField(choices=[('E', 'EXCELENTE'), ('B', 'BUENO'), ('R', 'REGULAR'), ('M', 'MALO')], max_length=2)),
                ('pregunta10', models.CharField(choices=[('E', 'EXCELENTE'), ('B', 'BUENO'), ('R', 'REGULAR'), ('M', 'MALO')], max_length=2)),
                ('sugerencias', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EncuestaMedicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateField(auto_now=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('hora_registro', models.TimeField(auto_now_add=True)),
                ('p1_matutino', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p1_vespertino', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p1_nocturno', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p1_fin', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p2_matutino', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p2_vespertino', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p2_nocturno', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p2_fin', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p3_matutino', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p3_vespertino', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p3_nocturno', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p3_fin', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p4_matutino', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p4_vespertino', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p4_nocturno', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p4_fin', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p5_matutino', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p5_vespertino', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p5_nocturno', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p5_fin', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p6_bacter', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p6_bioq_endocrino', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p6_hemato_onco', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p6_inmuno_genetica', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p6_inmuno_alergia', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p6_nefro', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p6_paramic', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p6_quim_clin_urg', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p6_viro', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p7', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=2)),
                ('p8', models.CharField(choices=[('MS', 'MUY SATISFECHO'), ('S', 'SATISFECHO'), ('I', 'INSATISFECHO'), ('MI', 'MUY INSATISFECHO')], max_length=2)),
                ('p9', models.CharField(choices=[('E', 'EXCELENTE'), ('B', 'BUENO'), ('R', 'REGULAR'), ('M', 'MALO')], max_length=2)),
                ('p10', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=2)),
                ('sugerencias', models.CharField(max_length=200)),
                ('clave_medico', models.CharField(max_length=20)),
                ('nombre_medico', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Area')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
