# Generated by Django 3.0.5 on 2021-03-31 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateField(auto_now=True, null=True)),
                ('hora_created', models.TimeField(auto_now_add=True, null=True)),
                ('usr_registra', models.CharField(max_length=20)),
                ('referencia', models.CharField(max_length=50)),
                ('expediente', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=45)),
                ('ap_paterno', models.CharField(max_length=45)),
                ('ap_materno', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('edad_ingreso', models.CharField(blank=True, max_length=50, null=True)),
                ('poliza', models.IntegerField()),
                ('curp', models.CharField(max_length=18)),
                ('folio', models.CharField(max_length=10)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_atencion', models.DateField()),
                ('fecha_egreso', models.DateField()),
                ('comentario', models.CharField(blank=True, max_length=250, null=True)),
                ('monto_recuperado', models.DecimalField(decimal_places=2, max_digits=6)),
                ('monto_erogado', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cie_cve1', models.CharField(choices=[('1', 'CIE-9'), ('2', 'CIE-10')], max_length=1)),
                ('cve_diag1', models.CharField(blank=True, max_length=10, null=True)),
                ('descrip_diag1', models.CharField(blank=True, max_length=200, null=True)),
                ('servicio_diag1', models.CharField(blank=True, max_length=200, null=True)),
                ('medico_diag1', models.CharField(blank=True, max_length=200, null=True)),
                ('cie_cve2', models.CharField(choices=[('1', 'CIE-9'), ('2', 'CIE-10')], max_length=1)),
                ('cve_diag2', models.CharField(blank=True, max_length=10, null=True)),
                ('descrip_diag2', models.CharField(blank=True, max_length=200, null=True)),
                ('servicio_diag2', models.CharField(blank=True, max_length=200, null=True)),
                ('medico_diag2', models.CharField(blank=True, max_length=200, null=True)),
                ('cie_cve3', models.CharField(choices=[('1', 'CIE-9'), ('2', 'CIE-10')], max_length=1)),
                ('cve_diag3', models.CharField(blank=True, max_length=10, null=True)),
                ('descrip_diag3', models.CharField(blank=True, max_length=200, null=True)),
                ('servicio_diag3', models.CharField(blank=True, max_length=200, null=True)),
                ('medico_diag3', models.CharField(blank=True, max_length=200, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Categoria')),
                ('entidad_federativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.EntidadFederativa')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.TipoEstatus')),
                ('procedencia_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.ProcedenciaPaciente')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.TipoPrograma')),
                ('tipo_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.TipoRegistro')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
