# Generated by Django 3.0.5 on 2021-03-31 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateField(auto_now=True, null=True)),
                ('calorias_totales', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('comensal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.TipoComensal')),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.TipoDieta')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.TipoServicio')),
            ],
            options={
                'verbose_name': 'Encabezado Menú',
                'verbose_name_plural': 'Encabezado de los Menús',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('calorias_totales', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.UnidadMedida')),
            ],
            options={
                'verbose_name': 'Encabezado Receta',
                'verbose_name_plural': 'Encabezado de la Recetas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RecetaDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('calorias', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Producto')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sidya.Receta')),
            ],
            options={
                'verbose_name': 'Detalle Receta',
                'verbose_name_plural': 'Detalles de las Recetas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MenuDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('calorias', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sidya.Menu')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Producto')),
            ],
            options={
                'verbose_name': 'Detalle Menú',
                'verbose_name_plural': 'Detalles de los Menús',
                'managed': True,
            },
        ),
    ]
